### ISSUE TITLE
Won't compile on Lion

### ISSUE THREAD

**Issue by ajp** [jofell/Photon---iPhoto-Blog-Export#1]
Heyo, thanks for posting this.

I'm new to Objective C, but I'm trying to get this to compile for Lion, just as a start.
I'm able to use the pre compiled plugin with iPhoto, but going forward if I want to make any changes and learn how,
I'll need to compile it. Any chance you've been working on this at all in the past few months?

Thanks!

**Comment by jofell** [comment]
Actually tye last Mac I had got soaked in the rain, and now I'm owning a Dell... hopefully soon I could get access to Mac OS X Lion myself to continue doing this.

But thanks for giving me a heads up. BTW, the project is written in XCode 3, so you might wanna download XCode 3 (instead of 4) if you really wanna build this.

Although if I get access to a Mac soon, I'll prolly change this to be compatible for newer XCode versions.

**Comment by ajp** [comment]
Gotcha. I'll give that a try if I can. If I can wrap my head around Objective C, this is definitely something I would like to help developer further.
